# Generated by Django 3.2.5 on 2021-08-10 17:03

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0002_borrowstate_donation_donationuser_userborrowstate_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='borrow_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lend_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserBorrowState',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
