# Generated by Django 3.2.5 on 2021-08-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0005_alter_userlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
