# Generated by Django 3.2.5 on 2021-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0007_auto_20210811_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowstate',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
