# Generated by Django 3.2.5 on 2021-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0008_alter_borrowstate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='target_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
