# Generated by Django 3.2.5 on 2021-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0009_auto_20210813_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
