# Generated by Django 3.2.5 on 2021-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0012_alter_userinfo_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcomment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
