# Generated by Django 3.2.5 on 2021-08-15 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lightup', '0015_communitycomment_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 15, 9, 15, 34, 708755, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lightup.communitypost'),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 15, 9, 15, 34, 707757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
