# Generated by Django 3.2.5 on 2021-08-18 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0018_auto_20210818_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='photo',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 18, 16, 26, 38, 357903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 18, 16, 26, 38, 356906, tzinfo=utc)),
        ),
    ]
