# Generated by Django 3.2.5 on 2021-08-19 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0019_auto_20210819_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='photo',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='donation',
            name='photo_content',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 21, 32, 0, 553396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 21, 32, 0, 552373, tzinfo=utc)),
        ),
    ]
